name = "GalacticDynamics"
uuid = "6ce81dba-b6c7-4d45-87bc-beb01d72eeef"
authors = ["Mart√≠n Mestre <mmestre@fcaglp.unlp.edu.ar> and contributors"]
version = "1.0.0-DEV"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticTools = "86c06d3c-3f03-46de-9781-57580aa96d0a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"
UnitfulChainRules = "f31437dd-25a7-4345-875f-756556e6935d"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
