name = "GalacticDynamics"
uuid = "6ce81dba-b6c7-4d45-87bc-beb01d72eeef"
authors = ["Mart√≠n Mestre <mmestre@fcaglp.unlp.edu.ar> and contributors"]
version = "1.0.0-DEV"

[deps]
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
